# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

# https://www.home-assistant.io/integrations/binary_sensor.workday/
platform: workday
name: workday
country: AU
workdays:
  - mon
  - tue
  - wed
  - thu
  - fri

