# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

---
timeout: &timeout
  # steps can run for circa an hour, maximum: if they haven't finished by then, there's probably some
  # deeper problem. A global timeout would be better
  # (https://github.com/buildkite/feedback/issues/170).
  timeout_in_minutes: 58

steps:
  - block: ":stop: Verify contents of pull-request before building!"
    if: build.pull_request.repository.fork

  - command: "buildkite-agent pipeline upload $(nix-build -A ops.ci)"
    label: ":pipeline:"

