# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

url: !secret huawei_lte_url_vodafone
username: !secret huawei_lte_username
password: !secret huawei_lte_password
