# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

# https://github.com/claytonjn/hass-circadian_lighting
circadian_lighting:
  interval: 600
  transition: 15

