# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

# Everything that doesn't have to be in the main configuration.yaml
homeassistant:
  customize: !include_dir_merge_named ../customizations/entities

  customize_domain: !include_dir_merge_named ../customizations/domainse
