# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

# https://www.home-assistant.io/integrations/speedtestdotnet/
speedtestdotnet:
  scan_interval:
    minutes: 30
