# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

# https://www.home-assistant.io/integrations/spotify/
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
