# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

platform: nsw_fuel_station
station_id: !secret nsw_fuel_station_id
fuel_types: ['DL', 'PDL']
