# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

# https://www.home-assistant.io/integrations/time_date/
platform: time_date
display_options:
  - 'time'
  - 'date'
  - 'date_time'
  - 'date_time_iso'
  - 'time_date'
  - 'time_utc'
  - 'beat'
